package io.eliteblue.erp.core.model.security;

public enum AuthorityName {
    ROLE_USER,
    ROLE_SYS_ADMIN,
    ROLE_CRM,
    ROLE_CRM_READ_ONLY,
    ROLE_EMPLOYEE_ASSIGN,
    ROLE_HR,
    ROLE_TIMETRACKING,
    ROLE_BILLING,
    ROLE_PAYROLL,
    ROLE_AREA_SEC_COM,
    ROLE_DETACHMENT_COM,
    ROLE_SHIFTING_COM,
    ROLE_INVENTORY_MGR,
    ROLE_MATERIAL_REQ,

    ROLE_HEAD_OPERATIONS,

    ROLE_CEO,

    ROLE_SCOUT_HEAD
}