package io.eliteblue.erp.core.constants;

public enum InventoryStatus {
    PENDING_ASC, APPROVED_ASC, REJECTED_ASC,
    PENDING_COO, APPROVED_COO, REJECTED_COO,
    PENDING_CEO, APPROVED_CEO, REJECTED_CEO,
    PENDING_SCT, APPROVED_SCT, REJECTED_SCT,
    PURCHASING_ACQUIRED, HEAD_OFFICE_CLEARANCE, FIELD_OFFICE_DELIVERY,
    RECIEVED_FOR_DISTRIBUTION, RECEIVED, DELIVERED
}
